apiVersion: apps/v1
kind: Deployment
metadata:
  name: assistant-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: assistant-api
  template:
    metadata:
      labels:
        app: assistant-api
    spec:
      containers:
        - name: assistant-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
